import Link from 'next/link'

const inclusions = ['Website or redesign', 'Landing page for one offer', 'Lead capture and tracking', 'CRM / pipeline setup', 'Instant response automation', '24-hour, 3-day, and 7-day follow-up', 'Booking calendar setup', 'Appointment reminders', 'Basic reporting dashboard', 'Team handover']

export default function GrowthServicePage() {
  return (
    <main className="bg-[#f7f9fb] text-slate-950">
      <section className="bg-white px-6 py-20 lg:px-10 xl:px-16"><div className="mx-auto max-w-[1480px]"><p className="text-xs font-bold uppercase tracking-[0.22em] text-blue-600">Main offer</p><h1 className="mt-4 max-w-4xl text-5xl font-semibold leading-[1.05] tracking-[-0.04em]">Website, Lead Generation & Appointment Growth System</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600">For businesses that need more qualified enquiries, faster response, clearer follow-up, and more booked appointments.</p><div className="mt-8 flex gap-3"><Link href="/audit" className="rounded-lg bg-blue-600 px-6 py-4 font-semibold text-white">Request Audit</Link><Link href="/pricing" className="rounded-lg border border-slate-200 px-6 py-4 font-semibold">View Pricing</Link></div></div></section>
      <section className="px-6 py-20 lg:px-10 xl:px-16"><div className="mx-auto grid max-w-[1480px] gap-8 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-8"><h2 className="text-2xl font-semibold">Who it is for</h2><p className="mt-4 leading-8 text-slate-600">Clinics, consultants, agencies, real estate teams, home services, law firms, training centres, and other appointment-driven businesses with valuable leads.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-8"><h2 className="text-2xl font-semibold">Problems solved</h2><p className="mt-4 leading-8 text-slate-600">Weak mobile websites, poor enquiry flow, missed WhatsApp messages, no CRM process, manual follow-up, no reminders, and unclear reporting.</p></div></div></section>
      <section className="bg-white px-6 py-20 lg:px-10 xl:px-16"><div className="mx-auto max-w-[1480px]"><h2 className="text-3xl font-semibold tracking-[-0.03em]">Detailed inclusions</h2><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{inclusions.map((item)=><div key={item} className="rounded-xl border border-slate-200 bg-slate-50 p-5 font-semibold"><span className="material-symbols-outlined mr-2 align-middle text-blue-600">check_circle</span>{item}</div>)}</div></div></section>
      <section className="px-6 py-20 lg:px-10 xl:px-16"><div className="mx-auto max-w-4xl text-center"><h2 className="text-3xl font-semibold">Ready to find the leaks?</h2><p className="mt-4 text-slate-600">Start with the audit and we’ll recommend the right package based on your current flow.</p><Link href="/audit" className="mt-8 inline-flex rounded-lg bg-blue-600 px-6 py-4 font-semibold text-white">Request Free Audit</Link></div></section>
    </main>
  )
}
